version: '3.8'

services:
  frontend:
    container_name: quasar_frontend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - quasar_network

networks:
  quasar_network:
    driver: bridge
